### ISSUE TITLE
Update executor api to allow for reporting of failure conditions

### ISSUE THREAD

**Issue by BenDoan** [unoacm/code_court#130]
Possible failure conditions:
- run timed out
- run gave too much output
- run gave no output
- invalid run parameters
- runtime error [maybe]
- compilation error [maybe]

This api will be used by the executor to report error conditions, and the defendant frontend to display error conditions.

**Comment by spacetag** [comment]
Here are a few more that might be useful:
https://icpcarchive.ecs.baylor.edu/index.php?option=com_content&task=view&id=14&Itemid=30
