### ISSUE TITLE
Misc admin user page issues

### ISSUE THREAD

**Issue by BenDoan** [unoacm/code_court#151]
A few nits/bugs with the recent admin user page PR:

- **All**: I'm not sure that the creation time is important enough to display on the main users table (it's also somewhat long), thoughts?
- **Micah**: Looks like you forgot to call .last_submit_time on the run objects in the main table
- **Micah**: Misc data might get fairly large (since it's json); I would remove that from the main table
- **Micah**: A password confirm might be nice, thoughts?
- **All**: This isn't super related to this change, but do we want a username field for the scoreboard? Other options are using the full name (might be very long), email (people feel weird about displaying their email, also may be long), using the email username (I kind of like this one, but it's not super orthodox). Thoughts?

**Comment by hacksmath** [comment]
I think we can drop the creation time and misc_data from the view page.
I should add a password confirmation box. It'll be good for last minute user additions/recreations.
And using the email handle on the scoreboard is a good idea. However, there could be duplicates.

**Comment by hacksmath** [comment]
Fixed by #152
