### ISSUE TITLE
Automate scraping version numbers of compilers

### ISSUE THREAD

**Issue by spacetag** [unoacm/code_court#167]
Showing compiler/interpreter versions to the users is something we should be doing, and we should probably automate that process.

I think the best way to do this would be to add a "version" and a "version_number_command" field to the Language model, with the "version" field being populated after startup. Then, the executor could request these commands on startup and send the results back to the courthouse.

This feature will also allow the executor to verify that all compilers are present.

**Comment by pgayee694** [comment]
643cde60c333b7952e4f83a1253b3dd37766b5f4
