### ISSUE TITLE
Verify that code_court runs under the windows subsystem for linux

### ISSUE THREAD

**Issue by BenDoan** [unoacm/code_court#233]
Please add instructions if it does.

**Comment by pgayee694** [comment]
On WSL, code_court runs. However, I encountered a lot of instances in which it would hang or freeze while installing packages or building the front-end. Additionally, docker is difficult to get to work, and I have not managed to get it to work. I tried this method: https://blogs.msdn.microsoft.com/commandline/2017/12/08/cross-post-wsl-interoperability-with-docker/ 
as well as another method, however to install docker on Windows 10, it requires either Professional or Enterprise. I think it should be fine to use with development, but I will test this further. 
The instructions I followed are those in the readmes for dev and production setup, with a few edits I added in #254

**Comment by pgayee694** [comment]
I attempted to use WSL for development. I did this by writing tests for the util.py functions. However, as docker does not run very easily on WSL, using postgres also becomes an issue. This prevents easy testing of functions and features that will be added during development. As a result, I don't see WSL as viable to use for development in it's current state.
