### ISSUE TITLE
Deleting a language fails

### ISSUE THREAD

**Issue by spacetag** [unoacm/code_court#73]
@BenDoan

**Comment by BenDoan** [comment]
Can't reproduce.

**Comment by spacetag** [comment]
If there is a foreign key in the database that references a language you are trying to delete, the server will produce an IntegrityError.

In order to mitigate confusion for the end user, we should return an HTTP 400 with a message saying something like "Cannot delete [Language] because it is still being used as a foreign key elsewhere"

**Comment by hacksmath** [comment]
Implemented error messages for deletes in #181
